// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TransactionResponseStatus.
const (
	QUEUED TransactionResponseStatus = "QUEUED"
)

// Valid indicates whether the value is a known member of the TransactionResponseStatus enum.
func (e TransactionResponseStatus) Valid() bool {
	switch e {
	case QUEUED:
		return true
	default:
		return false
	}
}

// TransactionRequest defines model for TransactionRequest.
type TransactionRequest struct {
	// Data Hex-encoded contract payload (e.g., 0xa9059cbb...)
	Data      string             `json:"data"`
	ToAddress string             `json:"to_address"`
	WalletId  openapi_types.UUID `json:"wallet_id"`
}

// TransactionResponse defines model for TransactionResponse.
type TransactionResponse struct {
	Status TransactionResponseStatus `json:"status"`
	TxId   openapi_types.UUID        `json:"tx_id"`
}

// TransactionResponseStatus defines model for TransactionResponse.Status.
type TransactionResponseStatus string

// Wallet defines model for Wallet.
type Wallet struct {
	Address  string             `json:"address"`
	WalletId openapi_types.UUID `json:"wallet_id"`
}

// SendTransactionJSONRequestBody defines body for SendTransaction for application/json ContentType.
type SendTransactionJSONRequestBody = TransactionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send a relayed transaction
	// (POST /v1/transactions/send)
	SendTransaction(c *gin.Context)
	// Create a new custodial wallet
	// (POST /v1/wallets)
	CreateWallet(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SendTransaction operation middleware
func (siw *ServerInterfaceWrapper) SendTransaction(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendTransaction(c)
}

// CreateWallet operation middleware
func (siw *ServerInterfaceWrapper) CreateWallet(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWallet(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/transactions/send", wrapper.SendTransaction)
	router.POST(options.BaseURL+"/v1/wallets", wrapper.CreateWallet)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFPBbhMxEP0Va+gBpM3utoVD91agiN6gUPVQlWpiT1pXu7Zrj5usovw7sjdpNyRcEEic1lrP87z35s0S",
	"pO2cNWQ4QLOEIO+pw3z87tEElKytuaDHSIHTX+etI8+aco1CxvylIL12qRYa+EyLCRlpFSkhrWGPkoXD",
	"vrWoxGsq78pC1As8qd+dyOm0LMs3UAD3jqCBwF6bO1gVwPYWlfIUcieHzOTT6z/qxTVOZqeTT/Xk5Gb5",
	"tl4d7IPPsW2Jb7VK6Jn1HTI0EKNWu9WrAjw9Ru1JQXM9gm6xKAa5N89wO30gyanZllfBWRNo16zAyDGf",
	"yMQuNfp6eXZ59nH04kj94o+oD7Bi02sf16usbpfef2D2hsIu7YTSZmbT+6y5TXdXND0WF9RiT16cmTtt",
	"SJx+OYcCnsiHIYqHZV3WiaF1ZNBpaOC4rMtjKJLI+6y2ejqs+GWAoQpkshBnh8wnlzBdnSto4BsZNZo3",
	"DHIo8Hur+lSeIk8mI9G5VsuMrR5CYrRZsXQ68DSDBl5VLztYrRew2rN9q23r2EfKP4a8ZSlH9dG/YbDO",
	"dKawveyjMoFSkmNSAo0Sj5EiqTzvELsOfb82T6DweWpKjGzPhWkUQyDC7wfwwRMyrWO8Y8DhXzNg3WGP",
	"5uFGyExEiRClpBBmsW37X/QOXAUKQ3MhY2CrNLZi/vz06mcAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
